### GET request to example server
GET http://localhost/api/greetings

###

GET http://localhost/api/validateSession

###

POST http://localhost/api/login
Content-Type: application/json

{
  "username": "Zeus",
  "password": "123456"
}
> {% client.global.set("token", response.body.token) %}
###

GET http://localhost/api/home


###

GET http://localhost/api/content/Clannad


###

GET http://localhost/api/content/Halo Fall of Reach


###

GET http://localhost/api/video/Clannad/Clannad-Ep1/Clannad-Ep1.mpd


###

GET http://localhost/api/video/Halo Fall of Reach/Halo Fall of Reach.mpd


###

GET http://localhost/

###