name: Build and upload artifact

on:
    workflow_call:
        inputs:
            gradle-build-task:
                description: 'Gradle task to build'
                required: true
                type: string
            output-path:
              description: 'Expected artifact output path'
              required: true
              type: string
            artifact-name:
              description: 'Artifact name to upload'
              required: true
              type: string

jobs:
    build:
        name: ${{inputs.artifact-name}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: setup java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '17'
                cache: gradle
            - name: Change wrapper permissions
              run: chmod +x ./gradlew
            - name: Run build task
              run: ./gradlew ${{inputs.gradle-build-task}}
            - name: Upload artifact
              uses: actions/upload-artifact@v4.4.0
              with:
                name: ${{inputs.artifact-name}}
                path: ${{inputs.output-path}}