name: Build android apk

on: 
    workflow_dispatch:
    workflow_call:
        inputs:
            gradle-build-task:
                required: true
                type: string
            output-path:
              required: true
              type: string

jobs: 
    build-android-apk: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: setup java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '17'
                cache: gradle
            - name: Change wrapper permissions
              run: chmod +x ./gradlew
            - name: Run build task
              run: ./gradlew ${{inputs.gradle-build-task}}
            - name: Upload artifact
              uses: actions/upload-artifact@v4.4.0
              with:
                name: android apk
                path: '${{inputs.output-path}}composeApp-debug.apk'